name: eky_pos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.4
  esc_pos_utils_plus: ^2.0.4
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  mobile_scanner: ^6.0.10
  open_filex: ^4.7.0
  percent_indicator: ^4.2.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  print_bluetooth_thermal: ^1.1.6
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  bloc: ^9.0.0
  dartz: ^0.10.1
  freezed_annotation: ^3.1.0
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/logo/
    - assets/images/
    - assets/images/products/
    - assets/images/logo/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/1024x.png"
  min_sdk_android: 21

